
spring:
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss
    time-zone: Asia/Seoul
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sample?useSSL=false&serverTimezone=Asia/Seoul
    username: root
    password: admin
    minimum-pool-size: 1
    maximum-pool-size: 1
    platform: mysql
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        default_schema: sample
  data:
    rest:
      default-page-size: 1000

server:
  port: 9292

logging:
  level:
    root: info
    com.sample: debug
    org:
      hibernate:
        type:
          descriptor:
           sql: trace
